### ISSUE TITLE
Add game information to game.ejs

### ISSUE THREAD

**Issue by linkret** [linkret/CrosseyCircley#23]
Currently, from a player's perspective it's unclear which player they are (O or X), and whose turn it is. This is mainly felt from the side of player X, while they're waiting for player O to make the first turn. It might feel like the site is broken/unresponsive.

We could use some new info messages, like, "You are player [Picture O/X]", or, "It's your turn!", or "It's the other player's turn!", stuff like that. There's enough space for this information somewhere around the game board. Above it may work the best? 

Also, this information could maybe be changed to "You won!" or "You lost!" when the game is over? The green/red colours already make this pretty obvious, but a textual message could work well in addition to that!

**Comment by LeaFranz** [comment]
@linkret  I would like to add this, could you assign this to me? Thanks!
